/**
 * Documentation Generator Script
 *
 * This script generates comprehensive markdown documentation from JSDoc comments
 * in the codebase. It creates a structured documentation site in the docs/ directory.
 */

const fs = require('fs');
const path = require('path');
const jsdoc2md = require('jsdoc-to-markdown');
const { glob } = require('glob');

const DOCS_DIR = path.join(__dirname, 'docs');
const SRC_DIR = path.join(__dirname, 'src');

// Documentation structure
const sections = [
  { name: 'API Services', pattern: 'src/services/**/*.js', output: 'api-services.md' },
  { name: 'Contexts', pattern: 'src/contexts/**/*.{js,jsx}', output: 'contexts.md' },
  { name: 'Hooks', pattern: 'src/hooks/**/*.js', output: 'hooks.md' },
  { name: 'Map Hooks', pattern: 'src/components/map/hooks/**/*.js', output: 'map-hooks.md' },
  { name: 'Utils', pattern: 'src/utils/**/*.js', output: 'utils.md' },
  { name: 'Map Utils', pattern: 'src/components/map/utils/**/*.js', output: 'map-utils.md' },
  { name: 'Components', pattern: 'src/components/**/*.{js,jsx}', output: 'components.md' },
];

/**
 * Ensure docs directory exists
 */
function ensureDocsDir() {
  if (!fs.existsSync(DOCS_DIR)) {
    fs.mkdirSync(DOCS_DIR, { recursive: true });
  }
}

/**
 * Generate documentation for a section
 */
async function generateSectionDocs(section) {
  console.log(`Generating documentation for: ${section.name}`);

  try {
    const files = glob.sync(section.pattern, { absolute: true });

    if (files.length === 0) {
      console.log(`  No files found for pattern: ${section.pattern}`);
      return;
    }

    console.log(`  Found ${files.length} files`);

    const markdown = await jsdoc2md.render({
      files: files,
      'heading-depth': 2,
      'example-lang': 'javascript',
      'no-cache': true
    });

    const header = `# ${section.name}\n\n`;
    const fileList = `## Files\n\n${files.map(f => `- ${path.relative(process.cwd(), f)}`).join('\n')}\n\n---\n\n`;
    const content = header + fileList + (markdown || `_No JSDoc documentation found in these files._\n\nTo add documentation, use JSDoc comments like:\n\n\`\`\`javascript\n/**\n * Function description.\n * @param {string} param - Parameter description\n * @returns {Object} Return value description\n */\n\`\`\``);

    const outputPath = path.join(DOCS_DIR, section.output);
    fs.writeFileSync(outputPath, content, 'utf8');
    console.log(`  ✓ Generated: ${section.output}`);
  } catch (error) {
    console.error(`  ✗ Error generating ${section.name}:`, error.message);
  }
}

/**
 * Generate index page
 */
function generateIndex() {
  const content = `# AtmoSwing Web Viewer - API Documentation

This documentation is automatically generated from JSDoc comments in the source code.

## 📚 Documentation Sections

${sections.map(s => `- [${s.name}](${s.output})`).join('\n')}

## 🚀 Project Overview

AtmoSwing Web Viewer is a React-based web application for visualizing atmospheric forecasts.
It provides interactive maps, time series charts, and analog date analysis tools.

### Key Features

- **Interactive Map Visualization**: OpenLayers-based map with WMTS layers and forecast points
- **Forecast Analysis**: View analog dates, distributions, and time series
- **Multiple Workspaces**: Support for different forecast regions and configurations
- **Runtime Configuration**: Dynamic configuration without rebuilding

### Technology Stack

- **React 19** with hooks and context
- **OpenLayers 10** for interactive mapping
- **Material-UI (MUI)** for UI components
- **D3.js** for data visualization and charts
- **Vite** for fast development and building
- **i18next** for internationalization

### Architecture

The application follows a modern React architecture:

- **Contexts**: Manage global state (config, forecasts, selections)
- **Hooks**: Encapsulate reusable logic (caching, API requests, map interactions)
- **Services**: Handle API communication with the backend
- **Utils**: Provide utility functions for data processing and formatting
- **Components**: UI building blocks organized by feature

### Getting Started

See the main [README.md](../README.md) for development instructions.

For information about contributing to the documentation, see [DOCUMENTATION.md](../DOCUMENTATION.md).

## 📝 Documentation Guide

All public APIs should be documented using JSDoc comments. Example:

\`\`\`javascript
/**
 * Fetches forecast data for a specific region and date.
 *
 * @param {string} region - The region identifier
 * @param {string} date - ISO date string
 * @returns {Promise<Object>} Forecast data object
 * @example
 * const data = await getForecast('alps', '2023-01-15');
 */
export async function getForecast(region, date) {
  // implementation
}
\`\`\`

---

*Last updated: ${new Date().toISOString()}*
*Generated by: \`npm run docs\`*
`;

  fs.writeFileSync(path.join(DOCS_DIR, 'README.md'), content, 'utf8');
  console.log('✓ Generated: README.md (index)');
}

/**
 * Main execution
 */
async function main() {
  console.log('🚀 Starting documentation generation...\n');

  ensureDocsDir();

  for (const section of sections) {
    await generateSectionDocs(section);
  }

  generateIndex();

  console.log('\n✅ Documentation generation complete!');
  console.log(`📁 Output directory: ${DOCS_DIR}`);
  console.log('\n💡 To view the documentation:');
  console.log('   - Open docs/README.md in your browser');
  console.log('   - Or run: npm run docs:serve');
}

main().catch(error => {
  console.error('❌ Fatal error:', error);
  process.exit(1);
});

